version: '3.8'

services:
  postgres:
    image: 'postgres:14.3'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=survey
    ports:
      - 54321:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/survey-data
