export const ErrorCodes = {
    API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
    DUPLICATE_FIELD_VALUE: 'DUPLICATE_FIELD_VALUE',
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    DUPLICATE_ERROR: 'DUPLICATE_ERROR',
    SERVER_ERROR: 'SERVER_ERROR'
};
export const ErrorCodeMap: { [key: string]: number } = {
    API_VALIDATION_ERROR: 400,
    DUPLICATE_FIELD_VALUE: 400,
    DATA_NOT_FOUND: 404,
    DUPLICATE_ERROR: 422,
    SERVER_ERROR: 500
};
